sudo: false
language: php
php:
  - '5.6'
before_install:
  - composer self-update
  - nvm install stable
  - nvm use stable
  - npm install -g grunt-cli
  - npm --version
  - node --version
install:
  - npm install phantomjs
  - npm install
before_script:
  - php src/lib/pre-install.php --non-interactive
script:
  - npm test
