sudo: false
language: php
php:
  - '5.6'
before_install:
  - composer self-update
  - nvm install 4.2.1
  - nvm use 4.2.1
  - npm install -g grunt-cli
  - npm --version
  - node --version
  - npm list -g
install:
  - npm install phantomjs-prebuilt
  - npm install
script:
  - npm test
